### PR TITLE
Error Bubbling

### LINKED ISSUE #1020: Custom scalar CoercionError clobbers parent messages
When a non-top level field has a custom scalar type that raises a coercion error. The coercion error message overwrites the parent's error message.

This gist shows the difference between a coercion returning nil, raising a `CoercionError`, and what the expected output would actually be.

https://gist.github.com/dnd/c9d6cbf18880f8fd916f962a7e10ca9e

This is from a block of code that looks like this:
```ruby
class SigninUser < GraphQL::Function
  CredentialsInputObject = GraphQL::InputObjectType.define do
    name 'CredentialsInputObject'

    argument :num, Scalars::Date
  end

  argument :credentials, !CredentialsInputObject
 
  ...
end
```
Please ignore the non-sensical use of the name `num`. :)

It would also be nice if instead of only displaying the coercion error message, that the error message be appended to the default string describing which field actually failed. Because as far as I can tell there is no way to determine inside of the coercion what the specific field, or parent is such as `num`, or `InputObject 'CredentialsInputObject'`.

```ruby
"Argument 'num' on InputObject 'CredentialsInputObject' has an invalid value. #{coercion_error.message}"
```

### LINKED ISSUE #1967: better error handling for required fields in an input object
consider something like:
```
input FooInput {
  bar: BarInput!
}
input BarInput {
  baz: BazInput!
}
input BazInput {
  bat: String!
}
```
if i leave out `bat` from my input i get an error like:
```
{      "message": "Argument 'baz' on InputObject 'BarInput' has an invalid value. Expected type 'BazInput!'.",
      "locations": [
        {
          "line": null,
          "column": null
        }
      ],
      "fields": [
        "mutation FooMutation",
        "fooMutation",
        "input",
        "bar",
        "baz"
      ]
    },
```
(sorry this may not be exact, i'm transposing from a work project)

i'd expect the missing required field (`bat`) to be the field referenced in the error message and the path, but currently that's not the case. i think the issue is here:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/literal_validator.rb#L26

since there's no actual ast node for the missing field, the error message that's generated comes from the parent input object.

### PR DESCRIPTION
**Pull request by modosc**
(this fixes #1020 and #1967) see also #160)

this pr adds a new schema option `error_bubbling`. with this set `true` (which is the default) the behavior is exactly the same as the current behavior, ie field errors bubble up to all the `InputObject`'s that contain them. 

with `error_bubbling false` this doesn't happen - we don't log static validation errors if the ast node that's invalid isn't the node we're visiting in `ArgumentLiteralsAreCompatible`. 

update: i merged in my branch that fixes #1967 as well.

### CODE REVIEW

File: lib/graphql/static_validation/literal_validator.rb [hunk 1]
```diff
@@ -10,28 +10,56 @@ def initialize(context:)
...
+            false
+          end
         end
       end
 
       private
 
+
+      def maybe_raise_if_invalid(ast_value)
+        ret = yield if block_given?
```
Comment (rmosolgo) [inline lib/graphql/static_validation/literal_validator.rb]: What's the use case for this method when there's no `block_given?` If it's never used that way, can we remove this check to make its intention a bit clearer?

File: lib/graphql/static_validation/rules/argument_literals_are_compatible.rb [hunk 2]
```diff
@@ -6,22 +6,52 @@ def validate_node(parent, node, defn, context)
         return if node.value.is_a?(GraphQL::Language::Nodes::VariableIdentifier)
         arg_defn = defn.arguments[node.name]
         return unless arg_defn
+        if !context.schema.error_bubbling
```
Comment (rmosolgo) [inline lib/graphql/static_validation/rules/argument_literals_are_compatible.rb]: I see the branches below have the same _happy path_, but different error handling, is that right? It looks like `LiteralValidationError` is only raised when `context.schema.error_bubbling` (because of the check in `maybe_raise_if_invalid`, is that right? 

If those assumptions are true, could this `if ... else ... end` be refactored to 

```
begin 
  # happy path as before
rescue GraphQL::CoercionError => err 
  # as before 
rescue GraphQL::LiteralValidationError => 
  # new error handling code 
end 
```

? If so, that would really help me keep track of what different behaviors we expect in different cases, and reduce some duplication!

File: lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb [hunk 3]
```diff
@@ -23,8 +23,8 @@ def validate_default_value(node, context)
           else
             begin
               valid = context.valid_literal?(value, type)
-            rescue GraphQL::CoercionError => err
-              error_message = err.message
+            rescue GraphQL::CoercionError, GraphQL::LiteralValidationError => err
+              error_message = err.message if err.is_a? GraphQL::CoercionError
```
Comment (rmosolgo) [inline lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb]: It looks like one kind of error should be handled one way, while another kind of error should be handled another way, is that right? Why not use different rescue clauses for this, for example 

```
begin 
  # ...
rescue GraphQL::CoercionError => err 
  # as before 
rescue GraphQL::LiteralValidationError 
  # do nothing, but don't let it propagate. 
end 
```

?

**Comment by modosc** [comment]
> The behavior that you've added here is much better than the previous behavior, what do you think about making it the new default ?

i'm ok with it - seems like it would make sense to do that in 1.9 but 1.8 probably should keep the current behavior? i'm also in the unenviable position of having to support the old behavior on a per-user basis for the time being so maybe that's where my conservatism comes from.

File: lib/graphql/static_validation/literal_validator.rb (hunk 1 above)
Comment (modosc) [reply lib/graphql/static_validation/literal_validator.rb]: i'll remove it - i guess it's just habit to add that.

Comment (rmosolgo) [reply lib/graphql/static_validation/literal_validator.rb]: Sure, I guess another option would be to _handle_ the no-block case, for example, by raising a descriptive error. That way, a future user would understand the intention there. I just wasn't sure if it was _supposed_ to work `if !block_given?` in this case, be cause it would _return_!

**Comment by rmosolgo** [comment]
>  unenviable position 

😅 

Sure, we can switch the default in 1.9.

File: lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb (hunk 3 above)
Comment (modosc) [reply lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb]: fixed.

File: lib/graphql/static_validation/literal_validator.rb (hunk 1 above)
Comment (modosc) [reply lib/graphql/static_validation/literal_validator.rb]: i agree that it shouldn't ever be called without a block so i just removed the ✔️

File: lib/graphql/static_validation/rules/argument_literals_are_compatible.rb (hunk 2 above)
Comment (modosc) [reply lib/graphql/static_validation/rules/argument_literals_are_compatible.rb]: i think i tried this at one point and ended up introducing some other bugs but it certainly seems like it should work. i'll try again now.

**Comment by modosc** [comment]
also out of curiosity - would you be open to migrating to rspec? test::unit / minitest make it so hard to do basic things like "just run this single spec"

**Comment by rmosolgo** [comment]
Did you try [`focus`](http://graphql-ruby.org/development#unit-tests) for running a single example? Personally I've been happy with minitest and I'm not excited about the operational shakeup of migrating test frameworks.

File: lib/graphql/static_validation/rules/argument_literals_are_compatible.rb (hunk 2 above)
Comment (modosc) [reply lib/graphql/static_validation/rules/argument_literals_are_compatible.rb]: ok - cleaned it up and found/fixed a bug that was somehow getting handled properly before.

**Comment by modosc** [comment]
> Did you try focus for running a single example? Personally I've been happy with minitest and I'm not excited about the operational shakeup of migrating test frameworks.

that solved my problem, thanks.

**Comment by modosc** [comment]
also, i started on #1967 and the fix is really just an extension of this (including gating off of `error_bubbling`. might make sense to put that in this branch too? right now i've just forked and i'll push the pr up later today, just a heads up.

**Comment by modosc** [comment]
i just tested this out with my company code and it looks like there's something not quite right. will update when i've sorted it out.

**Comment by modosc** [comment]
just figured it out -  bubbling was never tested or fixed for the `GraphQL::CoercionError` case. this should be a simple fix, working on it now.

**Comment by modosc** [comment]
ok, looks good on my end now.

**Comment by rmosolgo** [comment]
👌 😎  Thanks again for your work here! It's such a long-needed improvement and it really required a big effort. Looks great.

**Comment by modosc** [comment]
> 👌 😎 Thanks again for your work here! It's such a long-needed improvement and it really required a big effort. Looks great.

thanks! next time i'll squash first, i'm horrified to see a `wip` commit checked in.
