### PR TITLE
Use edge_class: with new pagination implementation

### LINKED ISSUE #3005: object.parent and/or edge_class not available to custom edges
**Describe the bug**

The current behavior for custom edge resolvers does not match the intended behavior [documented here](https://graphql-ruby.org/relay/connections.html#custom-edge-classes).

The documentation indicates that it is possible to define resolvers on custom edges which have access to `object.parent` (which is needed to locate rails "through relationships", for example). The documentation states that we are supposed to create a custom connection class which registers both a custom edge type class and custom edge class.

This doesn't work, as demonstrated below. The custom connection is successfully instantiated, and successfully instantiates the custom edge type class... but fails to instantiate the custom edge class, and object.parent is not available in the custom edge type class.

**Versions**

`graphql` version: graphql-1.10.10
`rails` (or other framework): rails-5.2.2.1
other applicable versions (`graphql-batch`, etc): graphql-batch-0.4.3

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
    class UserType < BaseObject
      field :id, GraphQL::Types::ID
      field :devices, UserDeviceConnection, null: false
    end

    class DeviceType < BaseObject
      field :os, GraphQL::Types::String
    end

    class UserDeviceConnection < GraphQL::Types::Relay::BaseConnection
      edge_type(UserDeviceEdgeType, edge_class: UserDeviceEdge)
    end

    class UserDeviceEdgeType < GraphQL::Types::Relay::BaseEdge
      node_type(Types::DeviceType)
      field :jwt_id, GraphQL::Types::String, null: true, method: :jwt_id
    end

    class UserDeviceEdge < GraphQL::Relay::Edge
      def initialize(node, connection)
        byebug #<< this never triggers
        super
      end

      def user_device
        @user_device ||= begin
          user = self.parent
          device = self.node
          UserDevice.where(user: user, device: device).first
        end
      end

      def jwt_id
        byebug #<< this never triggers
        user_device.jwt_id
      end
    end

# in app/models/device.rb
class Device
  #database fields -> id, os, ...
end

# in app/models/user.rb
class User
  #database fields -> id, name, ...
  has_many :devices, through: :user_devices
end

# in app/models/user_device.rb
class UserDevice
  #database fields -> user_id, device_id, jwt_id
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  users {      
    id
    devices {
      edges {
        jwtId # <<- everything else works, except this attribute. 
        node {
          os
        }
      }
    }
  }
}
```

```json
{
  "error": {
    "errors": [
      {
        "message": "        Failed to implement UserDeviceEdge.jwtId, tried:\n\n        - `GQL::Edges::UserDeviceEdgeType#jwt_id`, which did not exist\n        - `GraphQL::Pagination::Connection::Edge#jwt_id`, which did not exist\n        - Looking up hash key `:jwt_id` or `\"jwt_id\"` on `#<GraphQL::Pagination::Connection::Edge:0x0000555e9aefbed0>`, but it wasn't a Hash\n\n        To implement this field, define one of the methods above (and check for typos)\n"...
```

**Steps to reproduce**

Attempt to follow the documentation...

**Expected behavior**

object.parent should be accessible to resolvers in CustomEdgeType classes, or CustomEdge classes should be instantiated as documented.

</details>

**Additional context**

The following lines of code in the gem seem to ignore custom edge declarations. [BUG???]

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/relay/base_connection.rb#L109-L110

### PR DESCRIPTION
**Pull request by rmosolgo**
The new connection module didn't properly use `edge_class:` configurations.

Fixes #3005 
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3017

### CODE REVIEW

File: lib/graphql/pagination/connections.rb [hunk 1]
```diff
@@ -58,6 +58,7 @@ def all_wrappers
         @schema.ancestors.reverse_each do |schema_class|
           if schema_class.respond_to?(:connections) && (c = schema_class.connections)
             all_wrappers.merge!(c.wrappers)
+
```
Comment (rmosolgo) [inline lib/graphql/pagination/connections.rb:61]:
```suggestion
```
