### PR TITLE
Require selections on Unions, with backwards compat

### LINKED ISSUE #4351: `fields_have_appropriate_selections` does not require selections on union types
**Describe the bug**

The `fields_have_appropriate_selections` validation presently allows the following selection:

```graphql
query { myUnion }
```

With `myUnion` being a union type, this query returns the following payload:

```json
{ "data": { "myUnion": {} } }
```

The spec would require a union type to make a selection.

**Cause**

The issue occurs here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb#L34

The cause of the issue is that the [`fields?` check omits union types](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/type_kinds.rb#L70). To fix this validation, the check should use `composite?` instead of `fields?`.

**Steps to resolution**

Unfortunately this is a breaking change as sources that used to validate will now fail. Need to:

- Fix the relevant check.
- Hook breaking behavior to a schema-level setting for spec-compliance. Should also include https://github.com/rmosolgo/graphql-ruby/issues/4403

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #4351 

This implementation: 

- Warns if an invalid query is encountered and no compat mode is selected;
- Provides a hook for handing invalid queries (which can permit, deny, or provide a custom message) 
- Provides a config to reject invalid queries 

I think this is a safe default to roll out to anyone already using the gem.

cc @gmac -- finally...

### CODE REVIEW

File: lib/graphql/schema.rb [hunk 1]
```diff
@@ -1670,6 +1670,36 @@ def did_you_mean(new_dym = NOT_CONFIGURED)
...
 
+
+      # If you need to support previous, non-spec behavior which allowed selecting union fields
+      # but *not* selecting any fields on that union, set this to `true` to continue allowing that behavior.
+      #
+      # If this is `true`, then {.legacy_invalid_empty_selections_on_union} will be called with {Query} objects
+      # with that kind of selections. You must implement that method
+      # @param new_value [Boolean]
+      # @return [true, false, nil]
+      def allow_legacy_invalid_empty_selections_on_union(new_value = NOT_CONFIGURED)
```
Comment (gmac) [inline lib/graphql/schema.rb:1681]: These are probably worth noting in the guide docs given that you have to invoke the setting on your schema or experience an out-of-the-box warning. I suppose the future state defaults this to `true`, so maybe the oddity is sufficiently short-lived.

Comment (rmosolgo) [reply lib/graphql/schema.rb:1681]: Yes, it's a bummer to have a warning as the default behavior. But my guess is that this edge case is rarely encountered, since other GraphQL implementations (rightly) reject this -- like GraphiQL, for example.

Comment (gmac) [reply lib/graphql/schema.rb:1681]: Last I looked, we had about 30K / 5K RPM of these two cases (conflicting types / missing union selections), so plenty of clients in the world are running without client-side validation unfortunately.

Comment (gmac) [reply lib/graphql/schema.rb:1681]: Good question. Those observations were from over a year ago; I want to say there was ~6M RPM on that API back in those days? So yeah, not a significant total share, but still a lot of traffic. I'm setting up new metrics for this update so we can get a fresh sense of quantity and, more importantly, how many consumers they're coming from.

Comment (rmosolgo) [reply lib/graphql/schema.rb:1681]: The other interesting this would be how many _unique_ query strings. It could be so few query strings that you could basically hardcode a replacement query string for known "offenders" and then call it day.
