### PR TITLE
Fix field type description on List and NonNull

### LINKED ISSUE #2871: Error with introspection query including field type description
The following introspection query will error:

```graphql
query IntrospectionQuery {
  __schema {
    types {
      fields {
        type {
          description
        }
      }
    }
  }
}
```

It is breaking the usage of https://github.com/2fd/graphdoc/

**Versions**

`graphql` version: 1.10.6
`rails` version: 5

<details>
<summary>Click to view exception backtrace</summary>

```
RuntimeError:         Failed to implement __Type.description, tried:

        - `#<Class:0x00007f3b38163918>#description`, which did not exist
        - `GraphQL::Schema::NonNull#description`, which did not exist
        - Looking up hash key `:description` or `"description"` on `#<GraphQL::Schema::NonNull:0x0000558714c59478>`, but it wasn't a Hash

        To implement this field, define one of the methods above (and check for typos)

  from graphql/schema/field.rb:618:in `resolve_field_method'
  from graphql/execution/interpreter/runtime.rb:217:in `block (5 levels) in evaluate_selections'
  from graphql/tracing.rb:67:in `block in trace'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:81:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/backtrace/tracer.rb:45:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/schema/timeout.rb:81:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:67:in `trace'
  from graphql/execution/interpreter/runtime.rb:216:in `block (4 levels) in evaluate_selections'
  from graphql/query.rb:354:in `block in with_error_handling'
  from graphql/execution/errors.rb:30:in `with_error_handling'
  from graphql/query.rb:353:in `with_error_handling'
  from graphql/execution/interpreter/runtime.rb:215:in `block (3 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:367:in `block in resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:373:in `run_directive'
  from graphql/execution/interpreter/runtime.rb:367:in `resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:212:in `block (2 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:124:in `each'
  from graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:325:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:320:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:360:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:229:in `block (4 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:223:in `block (3 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:367:in `block in resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:373:in `run_directive'
  from graphql/execution/interpreter/runtime.rb:367:in `resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:212:in `block (2 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:124:in `each'
  from graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:325:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:320:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:360:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:346:in `block (2 levels) in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:343:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:336:in `each'
  from graphql/execution/interpreter/runtime.rb:336:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:229:in `block (4 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:223:in `block (3 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:367:in `block in resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:373:in `run_directive'
  from graphql/execution/interpreter/runtime.rb:367:in `resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:212:in `block (2 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:124:in `each'
  from graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:325:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:320:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:360:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:346:in `block (2 levels) in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:343:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:336:in `each'
  from graphql/execution/interpreter/runtime.rb:336:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:360:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:229:in `block (4 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:223:in `block (3 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:367:in `block in resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:373:in `run_directive'
  from graphql/execution/interpreter/runtime.rb:367:in `resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:212:in `block (2 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:124:in `each'
  from graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:325:in `block in continue_field'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:320:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:360:in `continue_field'
  from graphql/execution/interpreter/runtime.rb:229:in `block (4 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:223:in `block (3 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:367:in `block in resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:373:in `run_directive'
  from graphql/execution/interpreter/runtime.rb:367:in `resolve_with_directives'
  from graphql/execution/interpreter/runtime.rb:212:in `block (2 levels) in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:443:in `after_lazy'
  from graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:124:in `each'
  from graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
  from graphql/execution/interpreter/runtime.rb:60:in `run_eager'
  from graphql/execution/interpreter.rb:71:in `block in evaluate'
  from graphql/tracing.rb:67:in `block in trace'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:81:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/backtrace/tracer.rb:45:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/schema/timeout.rb:84:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:67:in `trace'
  from graphql/execution/interpreter.rb:70:in `evaluate'
  from graphql/execution/interpreter.rb:43:in `begin_query'
  from graphql/execution/multiplex.rb:113:in `begin_query'
  from graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
  from graphql/execution/multiplex.rb:83:in `map'
  from graphql/execution/multiplex.rb:83:in `run_as_multiplex'
  from graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
  from graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
  from graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
  from graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
  from graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
  from graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
  from graphql/execution/instrumentation.rb:72:in `call_hooks'
  from graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
  from graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
  from graphql/execution/instrumentation.rb:72:in `call_hooks'
  from graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
  from graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
  from graphql/execution/multiplex.rb:61:in `block in run_queries'
  from graphql/tracing.rb:67:in `block in trace'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
  from graphql/tracing.rb:81:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/backtrace/tracer.rb:30:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:83:in `block in call_tracers'
  from graphql/schema/timeout.rb:60:in `trace'
  from graphql/tracing.rb:83:in `call_tracers'
  from graphql/tracing.rb:67:in `trace'
  from graphql/execution/multiplex.rb:59:in `run_queries'
  from graphql/execution/multiplex.rb:49:in `run_all'
  from graphql/schema.rb:1626:in `multiplex'
  from graphql/schema.rb:1597:in `execute'
  from app/controllers/api/v2/graphql_controller.rb:5:in `execute'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:194:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:256:in `process_action'
  from active_record/railties/controller_runtime.rb:24:in `process_action'
  from abstract_controller/base.rb:134:in `process'
  from action_view/rendering.rb:32:in `process'
  from mini_profiler/profiling_methods.rb:78:in `block in profile_method'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:52:in `dispatch'
  from action_dispatch/routing/route_set.rb:34:in `serve'
  from action_dispatch/journey/router.rb:52:in `block in serve'
  from action_dispatch/journey/router.rb:35:in `each'
  from action_dispatch/journey/router.rb:35:in `serve'
  from action_dispatch/routing/route_set.rb:840:in `call'
  from skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
  from skylight/core/fanout.rb:25:in `instrument'
  from skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
  from omniauth/strategy.rb:192:in `call!'
  from omniauth/strategy.rb:169:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from flipper/middleware/memoizer.rb:62:in `memoized_call'
  from flipper/middleware/memoizer.rb:40:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/attack.rb:158:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/etag.rb:27:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/conditional_get.rb:40:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/head.rb:12:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/session/abstract/id.rb:266:in `context'
  from rack/session/abstract/id.rb:260:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/cookies.rb:670:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/callbacks.rb:28:in `block in call'
  from active_support/callbacks.rb:98:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from request_store/middleware.rb:19:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
  from rack/method_override.rb:24:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/runtime.rb:22:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from rack/sendfile.rb:110:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from action_dispatch/middleware/ssl.rb:74:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from mini_profiler/profiler.rb:171:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from skylight/core/probes/middleware.rb:34:in `call'
  from skylight/core/middleware.rb:98:in `call'
  from rails/engine.rb:524:in `call'
  from puma/configuration.rb:227:in `call'
  from puma/server.rb:675:in `handle_request'
  from puma/server.rb:476:in `process_client'
  from puma/server.rb:334:in `block in run'
  from puma/thread_pool.rb:135:in `block in spawn_thread'
```

</details>

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #2871

### CODE REVIEW

File: spec/graphql/schema/non_null_spec.rb [hunk 1]
```diff
@@ -55,4 +55,38 @@
...
+        field :strs, [String], null: false
+      end
+
+      query Query
+      use GraphQL::Execution::Interpreter
+      use GraphQL::Analysis::AST
+    end
+
+    it "doesn't break on description" do
+      res = NonNullIntrospectionSchema.execute(<<~GRAPHQL).to_h
```
Comment (rmosolgo) [inline spec/graphql/schema/non_null_spec.rb:71]:
```suggestion
      res = NonNullIntrospectionSchema.execute(<<-GRAPHQL).to_h
```
