### PR TITLE
Disallow casting of Enums into scalar values

### LINKED ISSUE #2371: Enum values should not be accepted as IDs
Hi!

Using the [example types of the documentation](https://graphql-ruby.org/getting_started):
```ruby
class QueryType < GraphQL::Schema::Object
  field :post, PostType, null: true do
    argument :id, ID, required: true
  end

  def post(id:)
    "Received request with id: #{id}"
  end
end
```
When using an argument of type ID, a query needs no quotation marks around the ID-value:
```ruby
{ post(id: 1) }

=> Received request with id: 1
```
This also holds true when characters are used as the ID:
```ruby
{ post(id: abc) }

=> Received request with id: abc
```
However, if the ID starts with a number followed by characters, we get an error:
```ruby
{ post(id: 1abc) }

=> #<GraphQL::Query::Result @query=... @to_h={"errors"=>[{"message"=>"Parse error on \"'\" (error) at [1, 15]", "locations"=>[{"line"=>1, "column"=>15}]}]}>
```
We can fix this, if we wrap quotation marks around the value:
```ruby
{ post(id: "1abc") }

=> Received request with id: 1abc
```

Is this behavior expected? If yes, is this documented somewhere?

### PR DESCRIPTION
**Pull request by daemonsy**
## What's up?

Happy Hacktoberfest 🎃 ! This resolves #2371. 

In general, it seems that we allow raw enum values to be coerced into strings, code below. 

```ruby
# in lib/graphql/scalar_type.rb
def raw_coercion_input(value)
  if value.is_a?(GraphQL::Language::Nodes::InputObject)
    value.to_h
  elsif value.is_a?(Array)
    value.map { |element| raw_coercion_input(element) }
  elsif value.is_a?(GraphQL::Language::Nodes::Enum)
    value.name
  else
    value
  end
end
```

This means that enum's value (#name) will be taken as a `string` to go through input coercion. But it seems that enums are not scalars, neither string or number from the spec. 

Hence I attempted a solution to reject enums as scalars. 

During validation, this returns errors such as the below: 

```ruby
"message"=>"Argument 'id' on Field 'milk' has an invalid value. Expected type 'ID!'.", 
"locations"=>[{"line"=>1, "column"=>17}], "path"=>["query getMilk", "milk", "id"], 
"extensions"=>{"code"=>"argumentLiteralsIncompatible", "typeName"=>"Field", "argumentName"=>"id"}}
```

### CODE REVIEW

File: spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb [hunk 1]
```diff
@@ -137,6 +137,40 @@
...
+      {
+        "message" => "Argument 'id' on Field 'cheese' has an invalid value. Expected type 'Int!'.",
+        "locations" => [{ "line" => 2, "column" => 3 }],
+        "path"=> ["query", "cheese", "id"],
+        "extensions"=> { "code" => "argumentLiteralsIncompatible", "typeName" => "Field", "argumentName" => "id" }
+      }
+    end
+
+    it "works with error bubbling disabled" do
+      without_error_bubbling(schema) do
```
Comment (daemonsy) [inline spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb]: I'm not sure what error bubbling does, just monkey see monkey do :)

File: lib/graphql/scalar_type.rb [hunk 2]
```diff
@@ -117,16 +117,14 @@ def raw_coercion_input(value)
         value.to_h
       elsif value.is_a?(Array)
         value.map { |element| raw_coercion_input(element) }
-      elsif value.is_a?(GraphQL::Language::Nodes::Enum)
```
Comment (daemonsy) [inline lib/graphql/scalar_type.rb]: With this, enums will never be treated as a scalar anymore. Practically, only ID and String types are affected as the casting for numeric types should reject this

**Comment by rmosolgo** [comment]
Thanks for digging in on this! I was afraid how complicated it might turn out to be, but I'm glad you found a straightforward solution.

**Comment by daemonsy** [comment]
Thanks @rmosolgo! This might affect some people who are relying on parsing enum into strings 🤞
