### PR TITLE
Mark queries as @executed when unhandled errors are raised

### LINKED ISSUE #1072: Infinite resolution when instrumenter inspects query result
Given the following conditions, I've run into an infinite loop when resolving a query. This is used to build tracing data, similar to https://github.com/uniiverse/apollo-tracing-ruby/blob/0ac17ca17f328ca13cee2ad29308874726f44f90/lib/apollo_tracing.rb#L62

* The query instrumenter inspects the query with `query.result` in `after_query`.
* The result throws an exception not inheriting a `GraphQL::ExecutionError`

This will prevent the multiplexer from executing [`finish_query`](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L90)as the [resolver](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L85) will raise an exception.

With an instrumenter, the [`ensure` block](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L182) will still execute. Note that `finish_query` has not set the query to [`executed`](https://github.com/rmosolgo/graphql-ruby/blob/72cf8d6fe637c2273730b1a6a16cd6431e4b08b7/lib/graphql/query.rb#L135). This will cause `after_query` to execute in a loop, since the multiplexer will never have the opportunity to set the query to `executed`.

I've attached a repro. This is on version 1.7.4.

```ruby
require 'graphql'

class QueryInstrumentation
  def before_query(query)
  end

  def after_query(query)
    puts query.result.to_json
  end
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :raiseExecutionError, types.String do
    resolve ->(object, args, ctx) {
      raise GraphQL::ExecutionError, "Whoops"
    }
  end

  field :raiseError, types.String do
    resolve ->(object, args, ctx) {
      raise GraphQL::Error, "Whoops"
    }
  end
end

MySchema = GraphQL::Schema.define do
  query QueryType
  instrument(:query, QueryInstrumentation.new)
end

MySchema.execute("{ raiseExecutionError }")
# {"data":{"raiseExecutionError":null},"errors":[{"message":"Whoops","locations":[{"line":1,"column":3}],"path":["raiseExecutionError"]}]}

MySchema.execute("{ raiseError }")
# `after_query': stack level too deep (SystemStackError)
```

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #1072

### CODE REVIEW

File: lib/graphql/execution/multiplex.rb [hunk 1]
```diff
@@ -91,6 +91,10 @@ def run_as_multiplex(multiplex)
             # Get the Query::Result, not the Hash
             query.result
           end
+        rescue StandardError
+          # Assign values here so that the query's `@executed` becomes true
+          queries.map { |q| q.result_values ||= nil }
+          raise $!
```
Comment (eapache) [inline lib/graphql/execution/multiplex.rb]: `raise` with no arguments will re-raise the rescued error automatically
