### PR TITLE
Fix field usage on prepared input types with original value

### LINKED ISSUE #4864: GraphQL::Analysis::AST::FieldUsage deprecated  argument detections for mutations raises an error when the InputType value is prepared
**Describe the bug**

`GraphQL::Analysis::AST::FieldUsage` deprecated argument detections for mutations is raising an error when the InputType value is prepared.

**Versions**

`graphql` version: 2.2.11

**Steps to reproduce**

```diff
diff --git a/spec/graphql/analysis/ast/field_usage_spec.rb b/spec/graphql/analysis/ast/field_usage_spec.rb
index 6e54ac38d..75e5dd635 100644
--- a/spec/graphql/analysis/ast/field_usage_spec.rb
+++ b/spec/graphql/analysis/ast/field_usage_spec.rb
@@ -254,6 +254,17 @@ describe GraphQL::Analysis::AST::FieldUsage do
     end
   end

+  describe "mutation with deprecated arguments with prepared values" do
+    let(:query_string) {%|
+      mutation {
+        pushValue(preparedTestInput: { deprecatedDate: "2020-10-10" })
+      }
+    |}
+
+    it "keeps track of nested deprecated arguments" do
+      assert_equal ['PreparedDateInput.deprecatedDate'], result[:used_deprecated_arguments]
+    end
+  end

   describe "when an argument prepare raises a GraphQL::ExecutionError" do
     class ArgumentErrorFieldUsageSchema < GraphQL::Schema
diff --git a/spec/support/dummy/schema.rb b/spec/support/dummy/schema.rb
index 206142cdb..d88b2d2ab 100644
--- a/spec/support/dummy/schema.rb
+++ b/spec/support/dummy/schema.rb
@@ -265,6 +265,18 @@ module Dummy
     argument :old_source, String, required: false, deprecation_reason: "No longer supported"
   end

+  class PreparedDateInput < BaseInputObject
+    description "Input with prepared value"
+    argument :date, String, description: "date as a string", required: false
+    argument :deprecated_date, String, description: "date as a string", required: false, deprecation_reason: "Use date"
+
+    def prepare
+      return nil unless date || deprecated_date
+
+      Date.parse(date || deprecated_date)
+    end
+  end
+
   class DeepNonNull < BaseObject
     field :non_null_int, Integer, null: false do
       argument :returning, Integer, required: false
@@ -490,6 +502,7 @@ module Dummy
     field :push_value, [Integer], null: false, description: "Push a value onto a global array :D" do
       argument :value, Integer, as: :val
       argument :deprecated_test_input, DairyProductInput, required: false
+      argument :prepared_test_input, PreparedDateInput, required: false
     end
     def push_value(val:)
       GLOBAL_VALUES << val
```

**Expected behavior**

`GraphQL::Analysis::AST::FieldUsage` can detect deprecated arguments within input objects in a mutation when there is a prepared field.

**Actual behavior**

Error is returned when an `InputType` argument is prepared

<details>
<summary>Click to view exception backtrace</summary>

```
Error:
GraphQL::Analysis::AST::FieldUsage::mutation with deprecated arguments with prepared values#test_0001_keeps track of nested deprecated arguments:
NoMethodError: undefined method `arguments' for #<Date: 2020-10-10 ((2459133j,0s,0n),+0s,2299161j)>
    lib/graphql/analysis/ast/field_usage.rb:52:in `block in extract_deprecated_arguments'
    lib/graphql/analysis/ast/field_usage.rb:39:in `each_pair'
    lib/graphql/analysis/ast/field_usage.rb:39:in `extract_deprecated_arguments'
    lib/graphql/analysis/ast/field_usage.rb:23:in `on_leave_field'
    lib/graphql/analysis/ast/visitor.rb:85:in `block in call_on_leave_field'
```

</details>

**Additional context**

I was looking on how to fix it, however it does not seems we can get to the unprepared arguments values from `GraphQL::Execution::Interpreter::ArgumentValue`

```
pry(#<GraphQL::Analysis::AST::FieldUsage>)> argument
=> #<GraphQL::Execution::Interpreter::ArgumentValue:0x000000010651f750 @default_used=false, @definition=#<GraphQL::Schema::Argument Mutation.pushValue.preparedTestInput: PreparedDateInput>, @value=#<Date: 2020-10-10 ((2459133j,0s,0n),+0s,2299161j)>>
```

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #4864 

Along the way, I noticed that `InputObject#prepare` was called twice when that method returned itself. By removing the first call, this solution worked out nicely.

### CODE REVIEW

File: lib/graphql/schema/input_object.rb [hunk 1]
```diff
@@ -215,8 +215,7 @@ def coerce_input(value, ctx)
             if resolved_arguments.is_a?(GraphQL::Error)
               raise resolved_arguments
             else
-              input_obj_instance = self.new(resolved_arguments, ruby_kwargs: resolved_arguments.keyword_arguments, context: ctx, defaults_used: nil)
-              input_obj_instance.prepare
```
Comment (calebpowell) [inline lib/graphql/schema/input_object.rb:219]: Hey @rmosolgo, we tried upgrading to the latest version of graphql ruby and we are seeing an error where input types aren't having their `prepare` method called. For example, one of our input types looks like this:

```Ruby
class CreditNoteLineItemInput < Types::BaseInputObject

    argument :amount, Types::MoneyInput, required: true, description: "The amount to credit."
    argument :charge_id,
             ID,
             required: true,
             loads: Types::Charge,
             as: :charge,
             description: "The charge being credited."

    def prepare
      { payable: charge, amount: amount }
    end
  end
```

When our unit tests run, input arguments for this type aren't being provided as a hash. I haven't had time to prepare a test case, but wondering if you may have introduced a bug on this PR?

Comment (rmosolgo) [reply lib/graphql/schema/input_object.rb:219]: I thought this bug might be related to both `loads:` and `def prepare` being used, but it's not that simple. I added a spec in c72f70078 and it passed. 

I'd like to track this down! Could you please open an issue with some details: 

- The source for the input object (shared above) 
- An example query which replicates the bug 
- The field where the input object is used 
- Anything else you think might be relevant 

Thanks!

Comment (engwan) [reply lib/graphql/schema/input_object.rb:219]: > When our unit tests run

How do your unit tests look like? Is this a unit test for the input object?

At GitLab, we had to update our unit tests because we were testing by calling `coerce_isolated_input`. The `#prepare` now happens outside of this method so we had to call `#prepare` manually. See https://gitlab.com/gitlab-org/gitlab/-/commit/4dc3e1866fc89387f1a7de004124751e0bda59fb

Comment (calebpowell) [reply lib/graphql/schema/input_object.rb:219]: I am taking another look and I think this problem may be related to some related libraries that we use at Shopify. I pulled the latest versions of all the Graphql gems we use and I am no longer seeing this error. Will report back and open an issue if I have anything definitive. Apologies for the false alarm.

Comment (rmosolgo) [reply lib/graphql/schema/input_object.rb:219]: No worries, please open a new issue if you find anything that we should investigate further :+1:
