### PR TITLE
Fix running multiple platform traces at once

### LINKED ISSUE #4542: Using multiple monitoring tools in GraphQL::Schema stopped working
**Describe the bug**

I'm trying to upgrade the graphql gem in my Rails application from version 2.0.16 to version 2.0.24. However, after the upgrade, I encountered an unexpected issue where the registration of multiple monitoring tools is no longer functioning as expected. Specifically, the capability to send traces to Appsignal and Datadog, which was previously working seamlessly, has ceased to operate.

I have reviewed the release notes, but I have not found any specific information regarding changes or limitations related to multiple monitoring tools registration. Therefore, I believe this issue may be a result of an unintended regression.

**Versions**

`graphql` version: 2.0.24
`rails` version: 7.0.5.1

**GraphQL::Schema**
```ruby
module Graph
  class Schema < GraphQL::Schema
    query Graph::Types::QueryType
    mutation Graph::Types::MutationType
    
    use GraphQL::Tracing::DataDogTracing, service: "graphql"
    use GraphQL::Tracing::AppsignalTracing
  end
end
```

**Steps to reproduce**

```ruby
# spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# frozen_string_literal: true

require "spec_helper"

module Appsignal
  module_function

  def instrument(key, &block); yield; end
  def instrumented; []; end
end

describe "Multiple monitoring tools" do
  module MultipleMonitoringToolsTest
    class Thing < GraphQL::Schema::Object
      field :str, String

      def str; "blah"; end
    end

    class Named < GraphQL::Schema::Union
      possible_types Thing
      def self.resolve_type(obj, ctx)
        Thing
      end
    end

    class Query < GraphQL::Schema::Object
      include GraphQL::Types::Relay::HasNodeField

      field :int, Integer, null: false

      def int
        1
      end

      field :thing, Thing
      def thing; :thing; end

      field :named, Named, resolver_method: :thing
    end

    class TestSchema < GraphQL::Schema
      query(Query)
      trace_with(GraphQL::Tracing::DataDogTrace)
      trace_with(GraphQL::Tracing::AppsignalTrace)
    end
  end

  it "returns GraphQL::Query::Result instance" do
    query = "{ int thing { str } named { ... on Thing { str } } }"
    assert_instance_of GraphQL::Query::Result, MultipleMonitoringToolsTest::TestSchema.execute(query)
  end
end
```

**Expected behavior**

```sh
➜  graphql-ruby git:(master) ✗  bundle exec rake test TEST=spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# Running tests with run options --seed 28696:

.

Finished tests in 0.001812s, 551.8764 tests/s, 551.8764 assertions/s.


1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Actual behavior**

Gem raises ArgumentError.

```sh
➜  graphql-ruby git:(master) ✗  bundle exec rake test TEST=spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# Running tests with run options --seed 41865:

E

Finished tests in 0.001901s, 526.0389 tests/s, 0.0000 assertions/s.


Error:
Multiple traces#test_0001_returns GraphQL::Query::Result instance:
ArgumentError: wrong number of arguments (given 2, expected 1)
...
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

<details>
<summary>Click to view exception backtrace</summary>

```
ArgumentError: wrong number of arguments (given 2, expected 1)
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:46:in `platform_execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:46:in `execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:47:in `block in execute_field'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:48:in `block in platform_execute_field'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:47:in `platform_execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:46:in `execute_field'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:541:in `block in evaluate_selection_with_resolved_keyword_args'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:538:in `evaluate_selection_with_resolved_keyword_args'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:449:in `evaluate_selection'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:380:in `block (2 levels) in evaluate_selections'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:379:in `block in evaluate_selections'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:378:in `each'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:378:in `evaluate_selections'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:284:in `block (4 levels) in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:283:in `block (3 levels) in run_eager'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:275:in `block (2 levels) in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:236:in `tap_or_each'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:266:in `block in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:257:in `run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:75:in `block (6 levels) in run_all'
    /graphql-ruby/lib/graphql/tracing/trace.rb:43:in `execute_query'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:47:in `block in execute_query'
    /graphql-ruby/spec/support/datadog.rb:52:in `trace'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:35:in `execute_query'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:34:in `block in execute_query'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:33:in `execute_query'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:74:in `block (5 levels) in run_all'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:62:in `block (4 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `each'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `each_with_index'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `block (3 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:171:in `block (2 levels) in each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:166:in `each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:170:in `block in each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:197:in `call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:169:in `each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:197:in `call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:45:in `block in run_all'
    /graphql-ruby/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:58:in `block in execute_multiplex'
    /graphql-ruby/spec/support/datadog.rb:52:in `trace'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:35:in `execute_multiplex'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:30:in `block in execute_multiplex'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:29:in `execute_multiplex'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:37:in `run_all'
    /graphql-ruby/lib/graphql/schema.rb:1084:in `multiplex'
    /graphql-ruby/lib/graphql/schema.rb:1060:in `execute'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:51:in `block (2 levels) in <top (required)>'

```

</details>

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #4542

### CODE REVIEW

File: lib/graphql/tracing/platform_trace.rb [hunk 1]
```diff
@@ -5,12 +5,22 @@ module Tracing
     module PlatformTrace
       def initialize(trace_scalars: false, **_options)
         @trace_scalars = trace_scalars
-        @platform_field_key_cache = Hash.new { |h, k| h[k] = platform_field_key(k) }
-        @platform_authorized_key_cache = Hash.new { |h, k| h[k] = platform_authorized_key(k) }
-        @platform_resolve_type_key_cache = Hash.new { |h, k| h[k] = platform_resolve_type_key(k) }
+
+        @platform_key_cache = Hash.new { |h, mod| h[mod] = mod::KeyCache.new }
```
Comment (rmosolgo) [inline lib/graphql/tracing/platform_trace.rb:9]: The basic gist of the problem is here: since all the modules are mixed into a single class, they share a single set of instance variables and method definitions. I addressed this problem in two ways: 

- Platform keys are now cached per-module, so each module can reference its own cached keys. 
- Platform keys aren't fetched from the trace object itself; instead, the platform trace module is mixed into a _new_ class, used only for getting those keys. That new class is assigned to `mod::KeyCache`.
