### PR TITLE
Don't pass NullValue to literal validation

### LINKED ISSUE #4307: `coerce_input` sometimes weirdly receives `GraphQL::Language` nodes
**Describe the bug**

I've found that while `coerce_input` _usually_ receives field arguments in their natural ruby form, occasionally it receives field arguments as `GraphQL::Language::Nodes::...` types.  This is unexpected (and it's hard to write a `coerce_input` to handle this case).

It seems to only happen when the argument is provided inline in the query (if you pass the argument as a query variable, it doesn't happen).  And while resolving a single query, it appears that `coerce_input` is called twice, and the scalar value doesn't agree in this case (once it's what I expect, and once it's in the `GraphQL::Language::Nodes::...` form).

On a side note, I found it a little surprising that every argument goes through `coerce_input` twice.  There's a potential optimization here where the coerced input is re-used instead of re-coercing the same input.

**Versions**

`graphql` version: 2.0.16 (also observable in 2.0.15, haven't tried on prior versions)
`rails` (or other framework): N/A
other applicable versions (`graphql-batch`, etc): N/A

**GraphQL schema**

See the inline script below for the SDL.

**GraphQL query**

See the inline script below for the query.

**Steps to reproduce**

put this into `graphql_ruby_bug.rb`:

``` ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.16"
end

require "graphql"

SCHEMA_STRING = <<~EOS
  scalar JsonValue

  type Query {
    echoJsonValue(arg: JsonValue): JsonValue
  }
EOS

class Application
  def initialize
    @schema = GraphQL::Schema.from_definition(SCHEMA_STRING, default_resolve: self)
  end

  def execute_query(query_string, **vars)
    puts "=" * 80
    puts "Executing query:"
    puts query_string
    puts

    @schema.execute(query_string, variables: vars)
  end

  def call(parent_type, field, object, args, context)
    args.fetch(:arg)
  end

  def coerce_input(type, value, ctx)
    ::JSON.generate(value).tap do |encoded|
      puts "coerced #{value.inspect} into #{encoded.inspect}"

      if ENV["SHOW_STACKTRACE"] && encoded.include?("#<GraphQL::Language::Nodes::NullValue")
        puts caller.join("\n")
      end
    end
  end

  def coerce_result(type, value, ctx)
    ::JSON.parse(value)
  end
end

app = Application.new

app.execute_query(<<~EOS, arg: [3, "abc", nil, 7])
  query WithArg($arg: JsonValue) {
    echoJsonValue(arg: $arg)
  }
EOS

app.execute_query(<<~EOS)
  query {
    echoJsonValue(arg: [3, "abc", null, 7])
  }
EOS
```

Run the script to reproduce.

**Expected behavior**

I expect to see this output:

```
================================================================================
Executing query:
query WithArg($arg: JsonValue) {
  echoJsonValue(arg: $arg)
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
================================================================================
Executing query:
query {
  echoJsonValue(arg: [3, "abc", null, 7])
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
```

**Actual behavior**

I get this output:

```
================================================================================
Executing query:
query WithArg($arg: JsonValue) {
  echoJsonValue(arg: $arg)
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
================================================================================
Executing query:
query {
  echoJsonValue(arg: [3, "abc", null, 7])
}

coerced [3, "abc", #<GraphQL::Language::Nodes::NullValue:0x0000000162af6d20 @line=2, @col=33, @filename=nil, @name="null">, 7] into "[3,\"abc\",\"#<GraphQL::Language::Nodes::NullValue:0x0000000162af6d20>\",7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
```

Notice the 3rd "coerced..." line--it shows that we got a `GraphQL::Language::Nodes::NullValue` object in our array, which feels like a bug.  (At the very least, it's undocumented behavior.) It's also surprising that `coerce_input` gets different values if the arg comes in via a query variable vs being inline--I wouldn't expect that.

If you re-run the script with `SHOW_STACKTRACE=1` you can see the callstack for this case:

<details>
<summary>Click to view stacktrace</summary>

```
tmp/graphql_ruby_bug.rb:37:in `tap'
tmp/graphql_ruby_bug.rb:37:in `coerce_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/build_from_definition.rb:305:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/build_from_definition.rb:305:in `block in build_scalar_type_coerce_method'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/scalar.rb:45:in `validate_non_null_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:45:in `block in recursively_validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:73:in `maybe_raise_if_invalid'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:44:in `recursively_validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:15:in `block in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:14:in `catch'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:14:in `validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validation_context.rb:41:in `validate_literal'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb:19:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/arguments_are_defined.rb:9:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:120:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/argument_names_are_unique.rb:9:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/required_arguments_are_present.rb:7:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:12:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_will_merge.rb:31:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_are_defined_on_type.rb:25:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:89:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/definition_dependencies.rb:47:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/subscription_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/query_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/mutation_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:13:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:44:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variable_names_are_unique.rb:20:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:18:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_will_merge.rb:26:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/operation_names_are_valid.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:59:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/definition_dependencies.rb:38:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:79:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:26:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragments_are_used.rb:6:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragments_are_finite.rb:6:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragment_names_are_unique.rb:17:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/operation_names_are_valid.rb:16:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/no_definitions_are_present.rb:34:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:68:in `visit'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:44:in `block (3 levels) in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:43:in `catch'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:43:in `block (2 levels) in validate'
/Users/myron/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:42:in `block in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:30:in `validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query/validation_pipeline.rb:71:in `ensure_has_validated'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query/validation_pipeline.rb:33:in `valid?'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query.rb:295:in `valid?'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:26:in `block (2 levels) in analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:25:in `map'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:25:in `block in analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:24:in `analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:53:in `block (3 levels) in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:44:in `block in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:37:in `run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema.rb:1018:in `multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema.rb:994:in `execute'
tmp/graphql_ruby_bug.rb:29:in `execute_query'
tmp/graphql_ruby_bug.rb:59:in `<main>'
```

</details>

### PR DESCRIPTION
**Pull request by rmosolgo**
Fixes #4307 

Oops, this probably should have been updated back when `null` was added to GraphQL, but it never was. 

When queries are running, this is handled by: https://github.com/rmosolgo/graphql-ruby/blob/4712a3d4c71ac7a36181a1a5da0d972b634137fe/lib/graphql/execution/interpreter/arguments_cache.rb#L96-L97

But during validation, we may not have a query running.

### CODE REVIEW

File: lib/graphql/static_validation/literal_validator.rb [hunk 1]
```diff
@@ -18,6 +18,22 @@ def validate(ast_value, type)
...
 
+      def replace_nulls_in(ast_value)
+        case ast_value
+        when Array
+          ast_value.map { |v| replace_nulls_in(v) }
+        when Hash
+          new_v = {}
+          ast_value.each do |k, v|
+            new_v[k] = replace_nulls_in(v)
+          end
```
Comment (myronmarston) [inline lib/graphql/static_validation/literal_validator.rb:29]: @rmosolgo I might be missing something here, but doesn't this need to be this?

``` ruby
new_v = {}
ast_value.each do |k, v|
  new_v[k] = replace_nulls_in(v)
end
new_v
```

The `new_v` after the `each` is needed so that it gets returned rather than the what `ast_value.each { }` returns (which is the original `ast_value`, IIRC).

Or you could do one of the following:

``` ruby
ast_value.each_with_object({}) do |(k, v), new_v|
  new_v[k] = replace_nulls_in(v)
end

# or:
ast_value.to_h do |k, v|
  [k, replace_nulls_in(v)]
end
```

...either of which avoids the problem by using a method that automatically returns the new hash.

Also, it looks like the test you added isn't able to detect this since it doesn't actually use a hash in the data.  Might be worth adding a hash w/ a null value to the array in the test case.

Comment (myronmarston) [reply lib/graphql/static_validation/literal_validator.rb:29]: ...actually, after writing that up I think there's an even simpler/better way to do this:

``` ruby
ast_value.transform_values { |v| replace_nulls_in(v) }
```

`transform_values` is like `map` for hashes, and seems ideal for this case.

Comment (rmosolgo) [reply lib/graphql/static_validation/literal_validator.rb:29]: So strange... If I comment out my changes: 
```ruby
            ruby_value = ast_value # replace_nulls_in(ast_value)
            type.validate_input(ruby_value, @context)
```

And run my tests, then that test _does_ fail: 

```
$ be rake test TEST=spec/graphql/schema/build_from_definition_spec.rb

# Running tests with run options --seed 27810:

F

Finished tests in 0.018214s, 54.9028 tests/s, 219.6113 assertions/s.


Failure:
GraphQL::Schema::BuildFromDefinition::JSON type#test_0001_Sends normal ruby values to schema coercion [/Users/rmosolgo/code/graphql-ruby/spec/graphql/schema/build_from_definition_spec.rb:1709]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1,6 @@
-[nil, nil]
+[#<GraphQL::Language::Nodes::NullValue:0xXXXXXX
+  @col=33,
+  @filename=nil,
+  @line=2,
+  @name="null">,
+ nil]


1 tests, 4 assertions, 1 failures, 0 errors, 0 skips
```

But ... It _shouldn't've_ worked, right?!

Oh, I see your point about not using a Hash. Derp, just a minute...

Comment (rmosolgo) [reply lib/graphql/static_validation/literal_validator.rb:29]: 💁‍♂️ https://github.com/rmosolgo/graphql-ruby/pull/4324
